service: some-food-api

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  tacos:
    handler: handler.tacos
    events:
      - http:
          path: /tacos
          method: get
